### ISSUE TITLE
Distribute marks across sub-prefixes of a shortest root prefix

### ISSUE THREAD

**Issue by pierky** [NICMx/mark-src-range#1]
This _trick_ looks very promising in terms of performance improvement, I look forward to test it and compare its results with the metrics I already gathered, but I have a request.

Is it feasible to distribute marks across sub-prefixes of a shorter one?

```
ip6tables -t mangle -A PREROUTING --source <PREFIX> -j MARKSRCRANGE [--mark-offset <OFFSET>] [--sub-prefix-len <SUB_PREFIX_LEN>]
```

So...

```
ip6tables -t mangle -A PREROUTING --source 2001:db8:1234:5600::/56 -j MARKSRCRANGE --sub-prefix-len 64
```

... should have the same effects of...

```
ip6tables -t mangle -A PREROUTING --source 2001:db8:1234:5600::/64 -j MARK --set-mark 0
ip6tables -t mangle -A PREROUTING --source 2001:db8:1234:5601::/64 -j MARK --set-mark 1
ip6tables -t mangle -A PREROUTING --source 2001:db8:1234:5602::/64 -j MARK --set-mark 2
...
ip6tables -t mangle -A PREROUTING --source 2001:db8:1234:56ff::/64 -j MARK --set-mark 255
```

With `--mark-offset`:

```
ip6tables -t mangle -A PREROUTING --source 2001:db8:1234:5700::/56 -j MARKSRCRANGE --sub-prefix-len 64 --mark-offset 256
```

```
ip6tables -t mangle -A PREROUTING --source 2001:db8:1234:5700::/64 -j MARK --set-mark 256
ip6tables -t mangle -A PREROUTING --source 2001:db8:1234:5701::/64 -j MARK --set-mark 257
...
```

Maybe I'm asking too much, but I think this would better fit to some real life scenarios.

**Comment by ydahhrk** [comment]
Ok, done.

The code is getting complicated, though; I should write a unit test.

In the meantime, you can test your configuration is interpreted properly by means of the new [validation mechanisms](https://github.com/NICMx/mark-src-range#configuration-testing).

**Comment by ydahhrk** [comment]
Unit test at https://github.com/NICMx/mark-src-range/tree/master/src/unit.

I did find an error! So remember to pull.
